@startuml

!define base #EFFFE9
!define accent #2EC4B6

!define green #5dd39e
!define violet #a5668b
!define cyan #06aed5

!define black #011627
!define white #FFFFF3

'Base'
skinparam {
  shadowing false
  backgroundColor white
  Arrow {
    Color     black
    FontColor black
  }
  Actor {
    FontColor black
    BackgroundColor base
    BorderColor     accent
  }
  Rectangle {
    FontColor black
    BackgroundColor white
    BorderColor     black
  }
}
'Activity'
skinparam activity {
  FontColor       black
  BackgroundColor base
  BorderColor     accent
  StartColor      black
  EndCOlor        black
  BarColor        black
  Diamond {
    FontColor       black
    BackgroundColor base
    BorderColor     accent
  }
}

'usecase'
skinparam usecase {
  FontColor       black
  BackgroundColor base
  BorderColor     accent
}
'class'
skinparam class {
  BackgroundColor base
  BorderColor     accent
}
skinparam package {
  BackgroundColor #FEFECE
  BorderColor     #A80036
}
skinparam stereotype {
  CBackgroundColor green
  ABackgroundColor cyan
  IBackgroundColor violet
}

'component'
skinparam component {
  FontColor       black
  BackgroundColor base
  BorderColor     accent
}
skinparam database {
  BackgroundColor white
  BorderColor     black
}
skinparam cloud {
  BackgroundColor white
  BorderColor     black
}
skinparam package {
  BackgroundColor white
  BorderColor     black
}
skinparam interface {
  BackgroundColor white
  BorderColor     black
}

'note'
skinparam note {

}

'state'
skinparam state {
  FontColor       black
  BackgroundColor base
  BorderColor     accent
  StartColor      black
  EndCOlor        black
}

'sequence'
skinparam sequence {
  ArrowColor accent
  LifeLine {
    BackgroundColor white
    BorderColor     accent
  }
  Participant {
    FontColor black
    BackgroundColor base
    BorderColor     accent
  }
}
@enduml
